### ISSUE TITLE
Module requires captcha

### ISSUE THREAD

**Issue by kingschnulli** [proudcommerce/psArticleRequest#12]
Seems like this module requires a captcha module to be present (https://github.com/OXIDprojects/captcha-module seems to work) - this should be a requirement in composer.json / metadata otherwise installation in >= 6.3 fails

Or did I miss something here?

**Comment by tabsl** [comment]
it´s already required?! https://github.com/proudcommerce/psArticleRequest/blob/feature/oxid6/composer.json#L22

**Comment by kingschnulli** [comment]
Oh well, missed that one - but doesn't help as long as you don't activate the captcha module. Maybe this could be a short notice in the readme. Or Oxid could come up with a solution in metadata.php. Sorry for bothering

**Comment by tabsl** [comment]
added notice zu readme ;-)
