### ISSUE TITLE
No delete button in admin list

### ISSUE THREAD

**Issue by metropolisdrachen** [proudcommerce/psArticleRequest#13]
I wondered why there is no delete button (trashcan symbol) in the admin list in Oxid Shop 6.1.5.
In Oxid 4.8.10 the delete button is an the last column from the list and in 6.1.5 the trashcan symbol is missing.

I figured out, that this is caused by the code in /Application/views/admin/tpl/psarticlerequest_admin_list.tpl
When the OXSHOPID is updated to "1" instead of "oxbaseshop" in the sql database the trashcan isn´t displayed
due to an assign of the var="readonly" according to "oxbaseshop".

I edited the code in psarticlerequest_admin_list.tpl from
 [{assign var="where" value=$oView->getListFilter()}] [{ if $shopid !=
"oxbaseshop" }] [{assign var="readonly" value="readonly disabled"}]
[{else}] [{assign var="readonly" value=""}] [{/if}
"

to 
 [{assign var="where" value=$oView->getListFilter()}] [{ if $shopid !=
"1" }] [{assign var="readonly" value="readonly disabled"}]
[{else}] [{assign var="readonly" value=""}] [{/if}]"

and then the trashcan symbol appears, so everything works fine then.

Maybe this is helpful for other users.

Kind regards,
Michael

**Comment by proudcommerce** [comment]
@Indianer3c please check ...
