### ISSUE TITLE
jqBootstrapValidation

### ISSUE THREAD

**Issue by jdlx** [proudcommerce/psArticleRequest#5]
Ihr benutzt hier https://github.com/proudcommerce/psArticleRequest/blob/master/copy_this/modules/proudsourcing/psArticleRequest/application/views/flow/tpl/form/ps_article_request_form.tpl#L1-L2 jqBootstrapValidation … dunno ob das in (neueren?) OX mit drinne ist, hier in einer 4.8.4 ist es nicht und folglich schepperts JS technisch sodaß slider und alles mögliche nicht mehr tun sobald die psArticleRequest form angezeigt wird … zumindest ein Hinweis im readme dahingehend wäre sinnvoll …

**Comment by tabsl** [comment]
das kam (damals) aus dem oxid standard ;-)
